### ISSUE TITLE
Rest Mode 11.00

### ISSUE THREAD

**Issue by Tazhys** [DeathRGH/frame4#3]
PS4 will not go into rest mode thus not allowing the ps4 to enter out of rest mode unless the power cable is removed and replugged back in.

**Comment by Tazhys** [comment]
Updated title

**Comment by DeathRGH** [comment]
There is no rest mode support. Even if you would make it back out of rest mode the threads would not be started again.
I will close the issue as rest mode support is something I will look into in the future but is not planned right now.
