### ISSUE TITLE
Setting watchpoint freezes game (FW 11.00)

### ISSUE THREAD

**Issue by mayizz** [DeathRGH/frame4#4]
Testing compatibility with the ps4 Tool Box 2.2.1.140 I experienced game freezes when setting a watchpoint for any given address in the debugger menu

**Comment by DeathRGH** [comment]
Does the game just pause or freeze and crash?
The debugger is obviously supposed to pause the game when it runs into a watchpoint.
If it however ends up crashing and producing logs, please provide them.

**Comment by mayizz** [comment]
the game just pauses. I didn't realize the watchpoint triggered. I expected a pop up like in ps4 reaper. Sorry for bothering you.
